const fs = require('fs');
let t = fs.readFileSync('src/world.js', 'utf8');
const NL = '
';
const a = [
  "    for (let i = 0; i < 2; i++) {",
  "      /* 楼梯口里程 = 站心 + SH.PLATFORM_EXITS[i]（单点）。下车人流读同一组值。 */",
].join(NL);
if (t.split(a).length !== 2) throw new Error('anchor');
const L = [];
L.push("    /* ================= 岛式站的**付费区上岛**（B 阶段第 3 层，§7.1）=================");
L.push("       付费区在**岛上方**：一块站厅板罩住整座岛（两缘各挑出 0.35 m），闸机线上板，");
L.push("       楼梯/扶梯从**两条缘口各自**上到板（每个出入口服务一条缘，交替布在 PLATFORM_EXITS）——");
L.push("       \"经楼梯下到两侧缘口\"就是这条动线。板上留洞给梯体穿上来，与走廊站厅同一套留洞口径。");
L.push("       走廊（正线外侧）那块板保留为非付费区/通道层，换乘通道与街面出口都在那一侧。 */");
L.push("    if (island) {");
L.push("      const MT = STATION_X.mezzTop, MTT = STATION_X.mezzT, VH = STATION_X.voidHalf;");
L.push("      /* 先布灯再写几何（与走廊站厅同一口教训）：板上/板下两排，沿岛两条缘各一列。 */");
L.push("      const LROWS = [board * (PLAT_FRONT + 1.3), board * (PLAT_FRONT + PLAT_W_ISL - 1.3)];");
L.push("      for (let ls = Math.ceil(s0 / 4) * 4; ls < s1; ls += 4) {");
L.push("        const f3 = al.frame(ls);");
L.push("        for (const lat of LROWS) {");
L.push("          const lp = al.world(f3, lat, MT - MTT - 0.22);");
L.push("          this.lg.add(lp[0], lp[1], lp[2], [0.90, 0.95, 1.0], 16, 0.95);");
L.push("          const hp = al.world(f3, lat, 5.30);");
L.push("          this.lg.add(hp[0], hp[1], hp[2], [0.90, 0.95, 1.0], 16, 0.9);");
L.push("        }");
L.push("      }");
L.push("      /* 梯口（沿线路）与留洞：两个 PLATFORM_EXITS 各服务一条缘，洞口 ±VH。 */");
L.push("      const exitsDz = SH.PLATFORM_EXITS.map(o => s + o);");
L.push("      const segsI = [];");
L.push("      let caI = s0;");
L.push("      for (const gz of exitsDz) {");
L.push("        if (gz - VH > caI) segsI.push([caI, gz - VH]);");
L.push("        caI = Math.max(caI, gz + VH);");
L.push("      }");
L.push("      if (caI < s1) segsI.push([caI, s1]);");
L.push("      for (const [a2, z2] of segsI) {");
L.push("        if (z2 - a2 < 1.5) continue;");
L.push("        const dp = al.frames(a2, z2, 6).map(f => { const q = al.world(f, board * (PLAT_FRONT + PLAT_W_ISL / 2), 0); return { p: q, r: f.r, u: f.u, f: f.f, s: f.s }; });");
L.push("        const HW = PLAT_W_ISL / 2 + 0.35;");
L.push("        this.b.sweep(dp, Geo.rectProfile(-HW, MT - MTT, HW, MT),");
L.push("          { mat: 'concrete', color: rgbOf('#aeb5b9'), closed: true, uvAlong: 1 / 2, vSpan: 1 / (PLAT_W_ISL + 0.7) });");
L.push("      }");
L.push("      /* 板的两条纵向板边：内缘栏板（有厚度的闭合截面）+ 竖向色檐口。 */");
L.push("      for (const E of edges) {");
L.push("        const lat = x => E.e + E.inw * x;");
L.push("        const bal = path.map(f => { const q = al.world(f, lat(-0.35), MT); return { p: q, r: f.r, u: f.u, f: f.f, s: f.s }; });");
L.push("        this.b.sweep(bal, [{ x: 0, y: 0, nx: 0, ny: 1 }, { x: E.inw * 0.06, y: 0, nx: 0, ny: 1 },");
L.push("          { x: E.inw * 0.06, y: 1.05, nx: 0, ny: -1 }, { x: 0, y: 1.05, nx: 0, ny: -1 }],");
L.push("          { mat: 'glassSoft', color: rgbOf('#9fd0dc'), closed: true, alpha: 0.45, uvAlong: 1 / 2, vSpan: 1 });");
L.push("        const fas = path.map(f => { const q = al.world(f, lat(-0.38), MT - MTT); return { p: q, r: f.r, u: f.u, f: f.f, s: f.s }; });");
L.push("        this.b.sweep(fas, [{ x: 0, y: 0, nx: E.inw, ny: 0 }, { x: E.inw * 0.06, y: 0, nx: E.inw, ny: 0 },");
L.push("          { x: E.inw * 0.06, y: 0.45, nx: E.inw, ny: 0 }, { x: 0, y: 0.45, nx: E.inw, ny: 0 }],");
L.push("          { mat: 'paint', color: rgbOf(color), closed: true, uvAlong: 1 / 3, vSpan: 1 });");
L.push("      }");
L.push("      /* 灯具本体（发光面板）：与光源同点位。 */");
L.push("      for (let ls = Math.ceil(s0 / 4) * 4; ls < s1; ls += 4) {");
L.push("        const f3 = al.frame(ls);");
L.push("        for (const lat of LROWS) {");
L.push("          const lo = al.world(f3, lat, MT - MTT - 0.03);");
L.push("          this.b.plate([lo[0], lo[1], lo[2]], [f3.f[0] * 2.2, f3.f[1] * 2.2, f3.f[2] * 2.2], [0, 0.12, 0], [0, -1, 0],");
L.push("            rgbOf('#eaf2f8'), { mat: 'emissive', uv: 1, emi: 1.35 });");
L.push("          const hi = al.world(f3, lat, 5.30);");
L.push("          this.b.plate([hi[0], hi[1], hi[2]], [f3.f[0] * 2.2, f3.f[1] * 2.2, f3.f[2] * 2.2], [0, 0.12, 0], [0, -1, 0],");
L.push("            rgbOf('#eef4f9'), { mat: 'emissive', uv: 1, emi: 1.5 });");
L.push("        }");
L.push("      }");
L.push("      /* 楼梯/扶梯：每个出入口一台扶梯，从**自己的那条缘**上到板。");
L.push("         _stepsUp 的横向自乘 side，岛在 −side ⇒ 传负的缘内距离。");
L.push("         近缘（i=0）从缘口向岛内升，远缘（i=1）从远缘向岛内升 —— 两条动线对称。 */");
L.push("      for (let i = 0; i < 2; i++) {");
L.push("        const dzI = exitsDz[i], frI = al.frame(dzI);");
L.push("        const riseI = STATION_X.mezzTop - 0.42, runI = riseI / Math.tan(STATION_X.escDeg * SH.DEG);");
L.push("        const edgeXf = i === 0 ? PLAT_FRONT + 0.5 : PLAT_FRONT + PLAT_W_ISL - 0.5;");
L.push("        const dirIn = i === 0 ? 1 : -1;                       // 向岛内");
L.push("        this._stepsUp(frI, side, -edgeXf, 0.42, -(edgeXf + dirIn * runI), STATION_X.mezzTop,");
L.push("          0, STATION_X.escLane, true);");
L.push("      }");
L.push("    }");
const b = L.join(NL) + NL + a;
t = t.replace(a, b);
fs.writeFileSync('src/world.js', t);
console.log('OK');
